# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/DigitalLogic_Lab/ALU_4bits_stu/ALU_4bits/ALU_4bits.cache/wt [current_project]
set_property parent.project_path D:/DigitalLogic_Lab/ALU_4bits_stu/ALU_4bits/ALU_4bits.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/DigitalLogic_Lab/ALU_4bits_stu/ALU_4bits/ALU_4bits.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  D:/DigitalLogic_Lab/ALU_4bits_stu/ALU_4bits/ALU_4bits.srcs/sources_1/new/alu.sv
  D:/DigitalLogic_Lab/ALU_4bits_stu/ALU_4bits/ALU_4bits.srcs/sources_1/new/fulladder.sv
  D:/DigitalLogic_Lab/ALU_4bits_stu/ALU_4bits/ALU_4bits.srcs/sources_1/new/rca.sv
  D:/DigitalLogic_Lab/ALU_4bits_stu/ALU_4bits/ALU_4bits.srcs/sources_1/imports/DLC/x7seg_d_port.sv
  D:/DigitalLogic_Lab/ALU_4bits_stu/ALU_4bits/ALU_4bits.srcs/sources_1/imports/DLC/ALU_4bits.sv
}
read_edif D:/DigitalLogic_Lab/ALU_4bits_stu/ALU_4bits/ALU_4bits.srcs/sources_1/imports/DLC/x7seg_d.edif
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/DigitalLogic_Lab/ALU_4bits_stu/ALU_4bits/ALU_4bits.srcs/constrs_1/imports/DLC/pin.xdc
set_property used_in_implementation false [get_files D:/DigitalLogic_Lab/ALU_4bits_stu/ALU_4bits/ALU_4bits.srcs/constrs_1/imports/DLC/pin.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top ALU_4bits -part xc7a35tftg256-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ALU_4bits.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ALU_4bits_utilization_synth.rpt -pb ALU_4bits_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
